### ISSUE TITLE
"name" should either not be optional or have a better default

### ISSUE THREAD

**Issue by socketbox** [pbs/terraform-aws-synthetics-module#24]
Currently, if I don't supply a name, the product name is used. But if I have multiple canaries for the same project, that's simply not an adequate default; when I attempt to create the second canary, it will fail.

Admittedly, the creation of an suitable default is complicated by the fact that the name is limited to 21 characters (?!), but by not obligating the user to decide upon a reasonable name, the module is inviting later rework.

**Comment by yhakbar** [comment]
The bucket names that are decided upon should be determined based on the `name` variable passed to this module if not explicitly set:
https://github.com/pbs/terraform-aws-synthetics-module/blob/main/snapshots.tf#L6

We generally only support prefixes if the underlying resource natively supports it:
https://github.com/pbs/terraform-aws-s3-module/blob/main/main.tf#L3

Using the `random` provider can result in some unnecessary overhead.

**Comment by socketbox** [comment]
>The bucket names that are decided upon should be determined based on the name variable passed to this module if not explicitly set:
https://github.com/pbs/terraform-aws-synthetics-module/blob/main/snapshots.tf#L6

Which makes obligating the user to choose a name all the more important, no?

**Comment by yhakbar** [comment]
> > The bucket names that are decided upon should be determined based on the name variable passed to this module if not explicitly set:
> > https://github.com/pbs/terraform-aws-synthetics-module/blob/main/snapshots.tf#L6
> 
> Which makes obligating the user to choose a name all the more important, no?

Not in my opinion. The benefit of not requiring the name variable is that if you are building a product, and you want one synthetic for your product, you can slot in the module with the required variables for tagging + canary script, and not worry about any other configurations.

If you get an error from setting up a second canary with the same name, or something, the name of the second canary can just be adjusted with something like `name = ${var.product}-other-reason-for-a-canary` or with a totally different name.

One of the goals for PBS Terraform modules is to minimize the number of decisions that you _have_ to make to get started. The more decisions you have to make to get started, the less likely you are to start with something that "just works", and iterate on with tweaks to make them optimal.

The drawback of doing this, as I understand it right now, is that you might get a name collision if you create two canaries for the same product without explicitly specifying a name for one of them. I think this is a good trade-off, as it saves cognitive overhead for the first canary, and works just the same as requiring the name input for the second canary.
